# Generated by Django 3.2 on 2025-11-06 03:33

from django.db import migrations, models
import django.db.models.deletion
import jobs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('job_types', '0002_alter_jobtype_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, default='sys', max_length=10, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=jobs.utils.now, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='departments.department')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job_types.jobtype')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-id'],
            },
        ),
    ]
