# Generated by Django 3.2 on 2026-04-14 00:00

from django.db import migrations, models
import activities.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("what", models.CharField(max_length=200)),
                ("where", models.CharField(max_length=300)),
                ("when", models.DateTimeField()),
                ("created_by", models.CharField(blank=True, default="sys", max_length=10, null=True)),
                ("updated_by", models.CharField(blank=True, default="sys", max_length=10, null=True)),
                ("date_created", models.DateTimeField(blank=True, default=activities.utils.now, null=True)),
            ],
            options={
                "verbose_name_plural": "Activities",
                "db_table": "activities",
                "ordering": ["-id"],
            },
        ),
    ]

