# Generated by Django 3.2 on 2025-11-06 05:24

import applicants.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('cover_letter', models.TextField()),
                ('valid_id', models.FileField(upload_to=applicants.utils.valid_id_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('resume', models.FileField(upload_to=applicants.utils.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20, null=True)),
                ('updated_by', models.CharField(blank=True, default='sys', max_length=10, null=True)),
                ('date_applied', models.DateTimeField(blank=True, default=applicants.utils.now, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'Applicants',
                'db_table': 'applicants',
                'ordering': ['-id'],
            },
        ),
    ]
