# Generated by Django 3.2 on 2025-11-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_auto_20251106_1340'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('email', 'job'), name='unique_applicant_per_job'),
        ),
    ]
