# Generated by Django 3.2 on 2025-11-07 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_applicant_unique_applicant_per_job'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicant',
            name='unique_applicant_per_job',
        ),
    ]
