# Generated by Django 3.2 on 2026-01-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_auto_20260113_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='verification_token',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
