# Generated by Django 3.2 on 2026-01-14 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_auto_20260113_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='full_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
