# Generated by Django 3.2 on 2026-04-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_auto_20260114_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
