# Generated by Django 3.2 on 2025-11-06 02:56

from django.db import migrations, models
import job_types.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=job_types.utils.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Job Types',
                'db_table': 'job_types',
                'ordering': ['-id'],
            },
        ),
    ]
