# Generated by Django 3.2 on 2025-12-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_types', '0002_alter_jobtype_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='updated_by',
            field=models.CharField(blank=True, default='sys', max_length=10, null=True),
        ),
    ]
