# Generated by Django 3.2 on 2025-11-06 03:19

import departments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='sys', max_length=10, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=departments.utils.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['-id'],
            },
        ),
    ]
