# Generated by Django 5.0.3 on 2024-03-26 09:23

from django.db import migrations

DEFAULT_TEMPLATES = {
    "applied": {
        "subject": "Job Application Received",
        "body": "Dear {applicant_full_name},<br><br>"
        "Thank you for applying for this position. "
        "Our HR team will reach out to you soon with further details.<br><br>"
        "Best Regards,<br>"
        "ILPI Recruitment Team.<br><br><br><br>",
    },
    "shortlisted": {
        "subject": "Job Application Shortlisted",
        "body": "Dear {applicant_full_name},<br><br>"
        "Congratulations! You have been shortlisted for the next phase of the recruitment process. "
        "Our HR team will reach out to you soon with further details.<br><br>"
        "Best Regards,<br>"
        "ILPI Recruitment Team.<br><br><br><br>",
    },
    "interview": {
        "subject": "Job Application Interview",
        "body": "Dear {applicant_full_name},<br><br>"
        "You are scheduled for an interview. "
        "Our HR team will reach out to you soon with further details.<br><br>"
        "Best Regards,<br>"
        "ILPI Recruitment Team.<br><br><br><br>",
    },
    "offered": {
        "subject": "Job Offer - {job_name}",
        "body": "Dear {applicant_full_name},<br><br>"
        "Congratulations! We are pleased to offer you the position. "
        "Our HR team will reach out to you soon with further details regarding the offer.<br><br>"
        "Best Regards,<br>"
        "ILPI Recruitment Team.<br><br><br><br>",
    },
    "hired": {
        "subject": "Job Application Status",
        "body": "Dear {applicant_full_name},<br><br>"
        "You are HIRED!. Welcome to the ILPI Family. "
        "Our HR team will reach out to you soon with further details.<br><br>"
        "Best Regards,<br>"
        "ILPI Recruitment Team.<br><br><br><br>",
    },
    "rejected": {
        "subject": "Job Application Status",
        "body": "Dear {applicant_full_name},<br><br>"
        "We are sorry to inform you that you did not make the cut. "
        "But thank you for applying.<br><br>"
        "Best Regards,<br>"
        "ILPI Recruitment Team.<br><br><br><br>",
    },
}


def populate_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("email_templates", "EmailTemplate")
    for status, data in DEFAULT_TEMPLATES.items():
        EmailTemplate.objects.create(
            name=status.replace("_", " ").title(),
            status=status,
            subject=data["subject"],
            body=data["body"],
        )


def reverse_populate_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("email_templates", "EmailTemplate")
    EmailTemplate.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("email_templates", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            populate_email_templates, reverse_populate_email_templates
        ),
    ]