# Generated by GPT-5.2 on 2026-01-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_templates", "0002_populate_email_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]


