"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta, timezone
import os
from dotenv import load_dotenv
import pymysql

UTC = timezone.utc

# import mimetypes

# mimetypes.add_type("text/css", ".css", True)

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_path = os.path.join(BASE_DIR, ".env")
load_dotenv(dotenv_path, override=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
if os.getenv("DEBUG") == "True":
    print("DEBUG IS ENABLED")
    DEBUG = True
if os.getenv("DEBUG") == "False":
    print("DEBUG IS DISABLED")
    DEBUG = False


def _split_env_list(name: str):
    raw = os.getenv(name, "")
    if not raw:
        return []
    return [item.strip() for item in raw.split(",") if item.strip()]


# Production hardening:
# - In dev (DEBUG=True), we allow all hosts/origins for convenience.
# - In prod (DEBUG=False), these must be explicitly set via env.
if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    # Example: ALLOWED_HOSTS=api.example.com,api.internal.example.com
    ALLOWED_HOSTS = _split_env_list("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "activities",
    "jobs",
    "applicants",
    "employees",
    "job_types",
    "departments",
    "notifications",
    "email_templates",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_celery_results",
    "django_celery_beat",
    "channels",
    "channels_redis",
    "django_filters",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    # django-cors-headers (v4+) prefers CORS_ALLOW_ALL_ORIGINS, but keep the legacy
    # alias too for safety.
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ORIGIN_ALLOW_ALL = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ORIGIN_ALLOW_ALL = False
    # Example: CORS_ALLOWED_ORIGINS=https://applicant.example.com,https://hr.example.com
    CORS_ALLOWED_ORIGINS = _split_env_list("CORS_ALLOWED_ORIGINS")

CORS_ALLOW_CREDENTIALS = True

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                ("127.0.0.1", 6379),
            ],
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": ("rest_framework.throttling.ScopedRateThrottle",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "EXCEPTION_HANDLER": "src.utils.custom_exception_handler",
    "DEFAULT_THROTTLE_RATES": {
        # Public applicant portal protections (IP-based for anonymous users)
        "public_applicant_submit": os.getenv("PUBLIC_APPLICANT_SUBMIT_RATE", "10/hour"),
        "public_applicant_verify": os.getenv("PUBLIC_APPLICANT_VERIFY_RATE", "60/hour"),
    },
}

ROOT_URLCONF = "src.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "src.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql_psycopg2",
    #     "OPTIONS": {"options": "-c search_path=hr"},
    #     "NAME": os.getenv("DEFAULT_NAME"),
    #     "USER": os.getenv("DEFAULT_USER"),
    #     "PASSWORD": os.getenv("DEFAULT_PASSWORD"),
    #     "HOST": os.getenv("DEFAULT_HOST"),
    #     "PORT": os.getenv("DEFAULT_PORT"),
    # },
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_TOKEN_MINUTES", "60"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_TOKEN_DAYS", "14"))
    ),
    "ROTATE_REFRESH_TOKENS": False,
    "ALGORITHM": "HS256",  # Default signing algorithm
    "SIGNING_KEY": SECRET_KEY,  # The key used to sign the token
    "AUTH_HEADER_TYPES": ("Bearer",),  # The authentication header prefix
}

# Celery Configuration
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"
CELERY_TIMEZONE = "Asia/Manila"
# Support both CELERY_BROKER_URL (new) and BROKER_URL (old) for backward compatibility
CELERY_BROKER_URL = (
    os.getenv("CELERY_BROKER_URL")
    or os.getenv("BROKER_URL")
    or "redis://127.0.0.1:6379/0"
)
CELERY_CACHE_BACKEND = "django-cache"

# Celery Beat Schedule
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "bulk-send-email-notifications": {
        "task": "notifications.tasks.bulk_send_email_nofication",
        "schedule": crontab(minute="*/5"),  # Run every 5 minutes
    },
    "cleanup-expired-application": {
        "task": "applicants.tasks.cleanup_expired_application",
        "schedule": crontab(
            hour=0,
            minute=0,
        ),
    },
    "send-daily-hr-report": {
        "task": "applicants.tasks.send_hr_report_email",
        "schedule": crontab(hour=8, minute=0),  # Run every day at 8:00 AM
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL") or "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,  # Ignore connection errors
        },
    },
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# Gmail: Port 465 uses SSL, Port 587 uses TLS
# Since .env uses port 465, we use SSL
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_PORT = os.getenv("EMAIL_PORT", "465")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_SSL_KEYFILE = None
EMAIL_SSL_CERTFILE = None
