# Generated by Django 3.2 on 2025-11-06 06:26

from django.db import migrations, models
import notifications.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='sys', max_length=10, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=notifications.utils.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Email Notifications',
                'db_table': 'email_notifications',
                'ordering': ['-id'],
            },
        ),
    ]
