# Generated by Django 3.2 on 2025-11-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
