# Generated by Django 3.2 on 2026-01-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailnotification_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if email sending failed', null=True),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='last_attempt',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last send attempt', null=True),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of resend attempts'),
        ),
    ]
